import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { loadLiveEngine } from '../scripts/live-engine-adapter.js';
import { currentVersionBare } from './support/release-identity.js';

const source = readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const index = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

function fixture({ basis = 'gross', finalHolesRule = 'continue', order = null, scores = null, choices = null, indexes = [0,0,0,0], allowBlindWolf = true } = {}) {
  const engine = loadLiveEngine();
  const holes = Array.from({ length: 18 }, (_, i) => ({ holeNumber: i + 1, par: 4, strokeIndex: i + 1, yardage: 400 }));
  const players = ['a','b','c','d'].map((id, i) => ({ id, name: `Player ${id.toUpperCase()}`, index: indexes[i] }));
  const course = { id: 'course', name: 'Wolf Club', tees: [{ id: 'tee', teeName: 'Blue', rating: 72, slope: 113, par: 72, holes }] };
  const defaults = { a: Array(18).fill(4), b: Array(18).fill(5), c: Array(18).fill(6), d: Array(18).fill(7) };
  const scoreSet = scores || defaults;
  const wolfInputs = {};
  holes.forEach((hole, i) => { wolfInputs[hole.holeNumber] = choices?.[i] || { choice: 'partner', partnerPlayerId: ['b','c','d','a'][i % 4], declaredAt: `2026-09-08T00:${String(i).padStart(2,'0')}:00Z` }; });
  const config = { key: 'wolf', basis, playerIds: ['a','b','c','d'], allowLoneWolf: true, allowBlindWolf, finalHolesRule, pointValue: 1, points: { teamWin:1, opponentsWin:1, loneWolfWin:4, loneWolfLoss:1, blindWolfWin:8, blindWolfLoss:1 }, handicapAllowanceMode:'recommended', handicapAllowancePercent:100 };
  const match = { id:'wolf-round', date:'2026-09-08', courseId:'course', teeId:'tee', holeCount:18, format:'teams', teamCount:2, playersPerTeam:2, featuredCompetition:'wolf', matchStatusGame:'wolf', playedHoleOrder: order || holes.map(h=>h.holeNumber), selectedGames:[config], wolfInputs, players: players.map((p,i)=>({ playerId:p.id, team:i<2?1:2, slot:i, teeId:'tee', scores:holes.map((h,j)=>({ holeNumber:h.holeNumber, gross:scoreSet[p.id]?.[j] ?? null })) })) };
  const state = engine.seedState({ players, courses:[course], matches:[match], activeMatchId:match.id });
  const live = state.matches[0];
  return { engine, match:live, metrics:engine.computeMatchMetrics(live), config:live.selectedGames[0] };
}

test('release identity and Wolf surfaces', () => { assert.equal(pkg.version, currentVersionBare); assert.match(source, /key: 'wolf', label: 'Wolf'/); assert.match(index, /id="wolfEntryWrap"/); assert.match(index, /id="wolfScorecardCard"/); });
test('normalization retains unknown fields and defaults', () => { const f=fixture(); const cfg=f.engine.normalizeWolfConfig({ key:'wolf' }); assert.equal(cfg.basis,'net'); assert.equal(cfg.pointValue,1); const row=f.engine.normalizeWolfHoleInput(f.match,{ choice:'lone', futureFact:7 },1,f.metrics); assert.equal(row.futureFact,7); });
test('rotation follows actual played position', () => { const order=[7,8,9,10,11,12,13,14,15,16,17,18,1,2,3,4,5,6]; const f=fixture({order}); assert.deepEqual(JSON.parse(JSON.stringify(f.engine.getWolfPlayOrder(f.match,f.metrics))),order); assert.equal(f.engine.getWolfPlayerIdForPosition(f.match,1,f.config),'a'); assert.equal(f.engine.computeWolfResults(f.match,f.metrics,f.config).holes[0].holeNumber,7); });
test('partner side win awards both partners', () => { const f=fixture(); const h=f.engine.computeWolfResults(f.match,f.metrics,f.config).holes[0]; assert.equal(h.winner,'wolf'); assert.deepEqual({...h.points},{a:1,b:1,c:0,d:0}); });
test('opponents win awards every opponent', () => { const scores={a:Array(18).fill(8),b:Array(18).fill(8),c:Array(18).fill(4),d:Array(18).fill(5)}; const f=fixture({scores}); const h=f.engine.computeWolfResults(f.match,f.metrics,f.config).holes[0]; assert.deepEqual({...h.points},{a:0,b:0,c:1,d:1}); });
test('halved hole awards zero and does not carry', () => { const tied={a:Array(18).fill(4),b:Array(18).fill(4),c:Array(18).fill(4),d:Array(18).fill(4)}; const f=fixture({scores:tied}); const r=f.engine.computeWolfResults(f.match,f.metrics,f.config); assert.equal(r.holes[0].winner,'tied'); assert.ok(Object.values(r.holes[0].points).every(n=>n===0)); assert.ok(Object.values(r.holes[1].points).every(n=>n===0)); });
test('Lone Wolf win uses configured award', () => { const choices=Array(18).fill(null).map(()=>({choice:'lone',declaredAt:'x'})); const f=fixture({choices}); assert.equal(f.engine.computeWolfResults(f.match,f.metrics,f.config).holes[0].points.a,4); });
test('Lone Wolf loss awards all three opponents', () => { const choices=Array(18).fill(null).map(()=>({choice:'lone',declaredAt:'x'})); const scores={a:Array(18).fill(8),b:Array(18).fill(4),c:Array(18).fill(5),d:Array(18).fill(6)}; const f=fixture({choices,scores}); assert.deepEqual({...f.engine.computeWolfResults(f.match,f.metrics,f.config).holes[0].points},{a:0,b:1,c:1,d:1}); });
test('Blind Wolf win uses configured award', () => { const choices=Array(18).fill(null).map(()=>({choice:'blind',declaredAt:'x'})); const f=fixture({choices}); assert.equal(f.engine.computeWolfResults(f.match,f.metrics,f.config).holes[0].points.a,8); });
test('Blind Wolf is rejected when disabled', () => { const f=fixture({allowBlindWolf:false}); const row=f.engine.normalizeWolfHoleInput(f.match,{choice:'blind',declaredAt:'x'},1,f.metrics); assert.equal(row.choice,''); });
test('invalid partner is rejected but blank partner remains editable', () => { const f=fixture(); assert.equal(f.engine.normalizeWolfHoleInput(f.match,{choice:'partner',partnerPlayerId:'z'},1,f.metrics).choice,''); assert.equal(f.engine.normalizeWolfHoleInput(f.match,{choice:'partner',partnerPlayerId:''},1,f.metrics).choice,'partner'); });
test('partial score keeps hole unresolved', () => { const scores={a:Array(18).fill(4),b:Array(18).fill(5),c:Array(18).fill(6),d:Array(18).fill(7)}; scores.d[0]=null; const f=fixture({scores}); const h=f.engine.computeWolfResults(f.match,f.metrics,f.config).holes[0]; assert.equal(h.scored,false); assert.equal(h.resolved,false); });
test('scored undeclared hole is a completion blocker', () => { const choices=Array(18).fill(null).map((_,i)=>i?{choice:'partner',partnerPlayerId:['b','c','d','a'][i%4],declaredAt:'x'}:{}); const f=fixture({choices}); const r=f.engine.computeWolfResults(f.match,f.metrics,f.config); assert.deepEqual(Array.from(r.unresolvedHoles),[1]); assert.equal(f.engine.getRoundDataCompletionState(f.match,f.metrics).gamesComplete,false); assert.equal(f.engine.areAllGamesFinal(f.match,f.metrics),false); });
test('net handicaps use one constant low reference', () => { const f=fixture({basis:'net',indexes:[0,10,20,30]}); const r=f.engine.computeWolfResults(f.match,f.metrics,f.config); assert.deepEqual({...r.gameHandicaps},{a:0,b:10,c:20,d:30}); assert.equal(r.lowGameHandicap,0); assert.equal(r.holes[0].values.d,5); });
test('continue final-hole rule repeats order one and two', () => { const f=fixture(); assert.equal(f.engine.getWolfPlayerIdForPosition(f.match,17,f.config),'a'); assert.equal(f.engine.getWolfPlayerIdForPosition(f.match,18,f.config),'b'); });
test('none final-hole rule has no Wolf and resolves scored holes', () => { const f=fixture({finalHolesRule:'none'}); const r=f.engine.computeWolfResults(f.match,f.metrics,f.config); assert.equal(r.holes[16].noWolf,true); assert.equal(r.holes[16].resolved,true); assert.ok(Object.values(r.holes[16].points).every(n=>n===0)); });
test('low-points assignments freeze and remain immutable', () => { const f=fixture({finalHolesRule:'low_points'}); f.match.holeFirstCompletedAt=Object.fromEntries(Array.from({length:17},(_,i)=>[String(i+1),`2026-09-08T00:${String(i).padStart(2,'0')}:00Z`])); f.engine.ensureWolfLifecycleFacts(f.match,f.metrics); const first=JSON.stringify(f.match.wolfFinalHoleAssignments); f.match.players[0].scores[0].gross=99; f.engine.ensureWolfLifecycleFacts(f.match,f.engine.computeMatchMetrics(f.match)); assert.equal(JSON.stringify(f.match.wolfFinalHoleAssignments),first); assert.ok(f.match.wolfFinalHoleAssignments['17']); assert.ok(f.match.wolfFinalHoleAssignments['18']); });
test('order lock is stamped after scoring starts', () => { const f=fixture(); f.engine.ensureWolfLifecycleFacts(f.match,f.metrics); assert.ok(f.match.wolfOrderLockedAt); });
test('head-to-head settlement is zero-sum and uses six pairs', () => { const f=fixture(); const r=f.engine.computeWolfResults(f.match,f.metrics,f.config); assert.equal(Object.values(r.amounts).reduce((a,b)=>a+b,0),0); assert.deepEqual(r.settlements,f.engine.optimalSettlementRows(r.amounts)); });
test('cloud serialization excludes Wolf and hydration ignores it', () => { const f=fixture(); assert.equal(f.engine.buildSelectedGamesForCloud(f.match).some(g=>g.key==='wolf'),false); assert.equal(f.engine.hydrateSelectedGamesFromCloud([{key:'wolf',playerIds:['a','b','c','d']},{key:'greenies'}]).some(g=>g.key==='wolf'),false); });
test('local-to-shared conversion fails closed', () => { const f=fixture(); const next=f.engine.setSharedMatchDraftMode({...f.match,storageMode:'local',sharedMatchEnabled:false},true); assert.equal(next.storageMode,'local'); assert.equal(next.sharedMatchEnabled,false); assert.equal(next.wolfSharedConversionBlocked,true); });
test('Story, payout, status and Ledger share computed Wolf facts', () => { const f=fixture(); const recap=f.engine.buildRoundRecapPayload(f.match,f.metrics); const payout=f.engine.getPayoutReportContext(f.match,f.metrics).payoutGames.find(g=>g.key==='wolf'); const ledger=f.engine.buildLedgerEntryReportModel(f.match,f.metrics).games.find(g=>g.type==='wolf'); assert.ok(JSON.stringify(recap).includes('wolf')); assert.deepEqual({...payout.amounts},{...f.engine.computeWolfResults(f.match,f.metrics,f.config).amounts}); assert.deepEqual({...ledger.totals},{...f.engine.computeWolfResults(f.match,f.metrics,f.config).totals}); assert.match(f.engine.buildLedgerEntryBody(f.match,f.metrics),/Wolf Ledger/); });
test('Classic and Player use one shared renderer and present-only save', () => { assert.equal((source.match(/renderWolfEntry\(match, hole, metrics\)/g)||[]).length>=2,true); assert.match(source,/const wolfChoiceControl = document\.querySelector\('\[data-wolf-choice\]'\)/); assert.match(source,/if \(isWolfEnabled\(match\) && wolfChoiceControl\)/); });
test('rules catalog exposes all six Wolf contract fields', () => { const f=fixture(); const contract=f.engine.getCompetitionRulesContract(f.match,f.config); ['scoringMethod','allowance','tieTreatment','stakeMeaning','escalation','finality'].forEach(key=>assert.ok(contract[key])); });
test('mixed games preserve Sixes while excluding only Wolf from cloud', () => { const f=fixture(); f.match.selectedGames.push({key:'sixes',mode:'points',basis:'gross',playerIds:['a','b','c','d'],pointValue:1}); const before=f.engine.computeSixesResults(f.match,f.metrics,f.match.selectedGames[1]); const cloud=f.engine.buildSelectedGamesForCloud(f.match); assert.ok(cloud.some(game=>game.key==='sixes')); assert.ok(!cloud.some(game=>game.key==='wolf')); const after=f.engine.computeSixesResults(f.match,f.metrics,f.match.selectedGames[1]); assert.deepEqual({...after.totals},{...before.totals}); });
test('setup visibly locks order after scoring and explains local-only availability', () => { assert.match(source,/Wolf is available for local scoring only in this release/); assert.match(source,/const orderLocked = !!editingMatch\?\.wolfOrderLockedAt/); assert.match(source,/Wolf order is locked because scoring has started/); });
